name : git hub actions push pr

on :
    push:
        branches:
            - main
            - "release/**"
        paths:
            - "src/**" 
    pull_request:
        branches:
            - main
            - "release/**"
        paths:
            - "src/**"        
jobs:
    example-job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v6.0.2
            - name: run tests
              run: npm test      


